V0.01
polosbl/Diploma pull request #1
Opened 2021-07-16 20:04 UTC by polosbl

2021-07-16 20:06 UTC, polosbl commented on src/test/java/tests/ProjectsTest.java
> +        String code = randomGenerators.randomId();
куда лучше убрать из тестов генератор рандомных имен?

2021-07-16 21:37 UTC, polosbl commented on src/test/java/tests/ProjectsTest.java
> +    @Test
вот такого плана тест с прекондишеном через API - созданием проекта.
как его лучше в page object распихать?)

2021-07-17 18:28 UTC, vchesnakoutest requested changes
please make fixes

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/adapters/BaseAdapter.java
> +                        .header("Token", System.getenv().getOrDefault("token", PropertyReader.getProperty("token")))
good approach 👍

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/adapters/BaseAdapter.java
> +                        .header("Content-Type", "application/json")
как вариант, строки "Content-Type" и "application/json" можно будет вынести в константы

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/adapters/BaseAdapter.java
> +    public Response post(String url, String body) {
тут наверное лучше возвращать String и потом в адаптерах его сериализовать в объект через gson. Как мы делали для метода get на занятии по QASE.

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +    }
молодец , что вынес метод сразу на BasePage.

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/DeleteProjectPage.java
> +    public ProjectsPage confirmDelete() {
я бы предложил назвать просто : clickDeleteProjectButton

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/DeleteSuiteModalPage.java
> +    public RepositoriesPage confirmDeleteSuite () {
тут тоже перименовал бы

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/DeleteTestCaseModalPage.java
> +public class DeleteTestCaseModalPage extends HeaderPage {
модалы должны наследовать BasePage, т.к это отдельные окна

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    }
предлагаю этот метод вынести в BasePage

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/RepositoriesPage.java
> +    @FindBy(xpath = "//*[@class='col text-start']//*[contains(text(), 'Update')]")
если возможно, я бы не привязывался к двум классам col и text-start, а только ко второму например, через contains. Так будет меньше зависимостей, соотв. надежнее локатор.

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/RepositoriesPage.java
> +        builder.moveToElement(driver.findElement(By.xpath(String.format(SUITE_HEADER, name)))).perform();
давай создадим в пакете utils класс CommonUtils или WebDriverUtils и эти два действия вынесем в отдельный статический метод, пример :  moveToElement(WebDriver driver, String element)

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/pages/RepositoriesPage.java
> +        builder.moveToElement(driver.findElement(By.xpath(String.format(SUITE_HEADER, name)))).perform();
тут соотв. будешь вызывать moveToElement из utils

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/utils/RandomGenerators.java
> +    public String randomId() {
сделай этот метод статическим и тебе не надо будет делать RandomGenerators randomGenerators = new RandomGenerators, можно будет сразу вызывать RandomGenerators.randomId()

2021-07-17 18:28 UTC, vchesnakoutest commented on src/main/java/utils/RandomGenerators.java
> +    public String randomCode() {
этот тоже сделай статическим

2021-07-17 18:28 UTC, vchesnakoutest commented on src/test/java/tests/ProjectsTest.java
> +        String code = randomGenerators.randomId();
сделай методы статичными, но передевать все равно из тестов будешь, просто без String name = randomGenerators.randomId();

2021-07-17 18:28 UTC, vchesnakoutest commented on src/test/java/tests/TestCaseTest.java
> +package tests;
создай для констант отдельный пакет лучше

2021-07-17 18:28 UTC, vchesnakoutest commented on src/test/java/tests/ProjectsTest.java
> +    @Test
API логику мы в page object не выносим, т.к. это Backend, там нету разделения на страницы. Единственное ты можешь сделай прослойку ApiSteps и там сделать степы для создания, удаления проектов и тд

2021-07-17 18:28 UTC, vchesnakoutest commented on src/test/java/tests/SuitsTest.java
> +        projectSteps
если тут во всех тестах надо удалять проект после выполнения теста, то можно в этом классе сделать AfterMethod, соотв. не надо будет дублировать код.

2021-07-17 18:28 UTC, vchesnakoutest commented on src/test/java/tests/LoginTest.java
> +                .openPage(BASE_URL)
давай сделаем метод, который будет по дефолту открывать BASE_URL, чтобы эту константу не передавать во всех тестах.

2021-07-19 17:07 UTC, merged